/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsExports = {
  aws_project_region: "ap-southeast-1",
  // aws_cognito_identity_pool_id: process.env.REACT_APP_COGNITO_IDENTITY_POOL_ID,
  // aws_cognito_region: "ap-southeast-1",
  // aws_user_pools_id: process.env.REACT_APP_COGNITO_USER_POOL_ID,
  // aws_user_pools_web_client_id:
  //   process.env.REACT_APP_COGNITO_USER_POOL_WEB_CLIENT_ID,
  // oauth: {},
  // aws_cognito_username_attributes: ["EMAIL", "PHONE_NUMBER"],
  // aws_cognito_social_providers: [],
  // aws_cognito_signup_attributes: ["EMAIL"],
  // aws_cognito_mfa_configuration: "OFF",
  // aws_cognito_mfa_types: ["SMS"],
  // aws_cognito_password_protection_settings: {
  //   passwordPolicyMinLength: 8,
  //   passwordPolicyCharacters: [
  //     "REQUIRES_LOWERCASE",
  //     "REQUIRES_NUMBERS",
  //     "REQUIRES_SYMBOLS",
  //     "REQUIRES_UPPERCASE",
  //   ],
  // },
  // aws_cognito_verification_mechanisms: ["EMAIL"],
  // aws_user_files_s3_bucket: process.env.REACT_APP_S3_UPLOAD_BUCKET,
  // aws_user_files_s3_bucket_region: "ap-southeast-1",
  // aws_appsync_graphqlEndpoint: "https://hrsjqstntd.execute-api.ap-southeast-1.amazonaws.com/graphql",
  // aws_appsync_region: "ap-southeast-1",
  // aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  // aws_cognito_login_mechanisms: ["EMAIL"],
};

export default awsExports;




// import { Amplify } from "aws-amplify";

// Amplify.configure({
//   aws_appsync_graphqlEndpoint: process.env.REACT_APP_APPSYNC_GRAPHQL_ENDPOINT,
//   aws_cognito_region: "ap-southeast-2",
//   aws_user_pools_id: process.env.REACT_APP_COGNITO_USER_POOL_ID,
//   aws_user_pools_web_client_id:
//     process.env.REACT_APP_COGNITO_USER_POOL_WEB_CLIENT_ID,
//   aws_cognito_identity_pool_id: process.env.REACT_APP_COGNITO_IDENTITY_POOL_ID,
//   aws_appsync_region: "ap-southeast-2",
//   aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
// });
